### ISSUE TITLE
Implement Get/Set system

### ISSUE THREAD

**Issue by davask** [davask/ComfyUI-MarasIT-Nodes#2]
allow use of get / set node for Bus 
allow get to bus only if origin set is Bus node from our node
allow connection from bus only for set node or our node

**Comment by kattamaran** [comment]
or .. send and receive the bus remotly from a given specific anybus node

**Comment by davask** [comment]
Hi @kattamaran , thx for your input :) 

Could you elaborate, I'm not sure how you would like to implement this ?
do you have a reference node I can check to see what you mean, and if you have time some screenshot would be awesome.

**Comment by davask** [comment]
This is fixed using the Set/Get node from KJNodes
