### ISSUE TITLE
Images won't pipe, throws tuple error.

### ISSUE THREAD

**Issue by RangerFrank** [davask/ComfyUI-MarasIT-Nodes#24]
Failed to validate prompt for output 2621:
* (prompt):
  - Exception when validating node: tuple index out of range
* PreviewImage 2621:
  - Exception when validating node: tuple index out of range
Output will be ignored
Failed to validate prompt for output 2584:
* (prompt):
  - Required input is missing: images
* Image Save 2584:
  - Required input is missing: images
Output will be ignored

**Comment by davask** [comment]
Hi @RangerFrank , if you had a workflow to share to reproduce your error that would be cool
